### ISSUE TITLE
Add Followup scaffold

### ISSUE THREAD

**Issue by kbuffardi** [ChicoState/CueFinder#10]
Followup will be used to handle multiple choice questions like the examples:

Do you feel like eating this food right now?
* I don’t want it at all
* I want it a little
* I want it a lot
* I need to eat it now

Clients want these questions to have radio buttons for each option and a Next button (just like the Next button for the Finder page). This page will NOT be timed. You will only ever be able to select one option (hence radio buttons) and MUST choose one option.

It is safe to assume all Followup questions will have 4 (or fewer) possible answers, but we want to be able to parameterize each answer's text.

**Comment by kbuffardi** [comment]
UPDATES: Name "FollowupQ" MCQ instead. It will "have many" relationship with a Choice model, where each choice has:
* Text (of the answer displayed)
* Order (to control order in which they're displayed)

MCQ will additionally have the following boolean properties:

* **MustChoose** whether or not the user has to choose an option
* **AllThatApply** whether the user can choose all options that apply, or just one option

**Comment by megglymark** [comment]
For this issue the bottom two bullet points are not yet implemented. Based on the most recent doc I don't believe they are necessary.

**Comment by kbuffardi** [comment]
For questions 13 and 14:

> 13. Which object is best for cutting vegetables from these choices?
> (Click one)
> 14. Which food or drink do you crave the most from these choices?
> (Click one)

Both need to be...
MustChoose = True
AllThatApply = False

When MustChoose == True, then we'll have to disable the timer and disable the "None of These" since the user has to choose one and only one.

However, the other Food Finder questions (17-20, 24-34) will need to be
MustChoose = False
AllThatApply = True

**Comment by kbuffardi** [comment]
Scratch that. I just realized this is the MCQ scaffold and not the FoodFinder one. It looks like you already took care of these features in Finder with `multipleChoice` and `noneEnabled`
