### ISSUE TITLE
Record a selection for when a Finder page first loads

### ISSUE THREAD

**Issue by kbuffardi** [ChicoState/CueFinder#19]
When the finder page loads, record a selection with 
row=-1 
col=-1 
count=-1

to indicate the start of the question.

**Comment by megglymark** [comment]
Should there be another another selection for when the time ends? For the beginning it can be 
row=-1 
col=-1 
count=-1
selected=1 (new boolean from issue#16)

And the end can be:
row=-1 
col=-1 
count=-1
selected=0

**Comment by megglymark** [comment]
Do you want this to start when images are shown or when the question is shown?

**Comment by kbuffardi** [comment]
Yes, the plan for time beginning and the time ends is good. 

The timer should start once the page with the images is loaded (after the user has already hit "ready")
